/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account */
        get: operations["account_api_account_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Breakdown */
        get: operations["breakdown_api_analytics_breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Costs */
        get: operations["costs_api_analytics_costs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audits */
        get: operations["audits_api_audits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Audit */
        post: operations["run_audit_api_audits_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit */
        get: operations["audit_api_audits__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauth */
        post: operations["reauth_api_auth_reauth_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bars */
        get: operations["bars_api_bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commands/{command_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Command */
        get: operations["command_api_commands__command_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        /** Put Config */
        put: operations["put_config_api_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config Versions */
        get: operations["config_versions_api_config_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decisions */
        get: operations["decisions_api_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision */
        get: operations["decision_api_decisions__decision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engine/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Engine Command */
        post: operations["engine_command_api_engine_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Equity */
        get: operations["equity_api_equity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/vault": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vault Exports
         * @description Weekly review notes waiting for the Mac (scripts/pull_vault_reviews.py), newest first.
         */
        get: operations["vault_exports_api_exports_vault_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/vault/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vault Export */
        get: operations["vault_export_api_exports_vault__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Features
         * @description The rule-usable features (entry-time, known before the rules run) for the rule editor.
         */
        get: operations["features_api_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Llm Usage */
        get: operations["llm_usage_api_llm_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Logs
         * @description The tail of the engine's JSON log (read-only), newest last.
         */
        get: operations["logs_api_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Positions */
        get: operations["positions_api_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Position */
        post: operations["close_position_api_positions__position_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rulebook/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rulebook Versions */
        get: operations["rulebook_versions_api_rulebook_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rulebook/versions/{version}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rulebook Diff */
        get: operations["rulebook_diff_api_rulebook_versions__version__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rules */
        get: operations["rules_api_rules_get"];
        put?: never;
        /** Create */
        post: operations["create_api_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rule */
        get: operations["rule_api_rules__rule_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{rule_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_rules__rule_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{rule_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_rules__rule_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{rule_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire */
        post: operations["retire_api_rules__rule_id__retire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System */
        get: operations["system_api_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trades */
        get: operations["trades_api_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades/{trade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trade */
        get: operations["trade_api_trades__trade_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/virtual-trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Virtual Trades */
        get: operations["virtual_trades_api_virtual_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountOut */
        AccountOut: {
            /** As Of */
            as_of: string | null;
            /** Balance */
            balance: string | null;
            /** Day Pnl */
            day_pnl: string | null;
            /** Drawdown Pct */
            drawdown_pct: string | null;
            /** Equity */
            equity: string | null;
            /** Free Margin */
            free_margin: string | null;
            /** Heat Pct */
            heat_pct: string | null;
            /** Limits */
            limits: components["schemas"]["LimitHeadroom"][];
            /** Margin */
            margin: string | null;
            /** Open Positions */
            open_positions: number;
            /** Open Risk Money */
            open_risk_money: string | null;
        };
        /** AuditRunDetail */
        AuditRunDetail: {
            /** Candidates */
            candidates: unknown[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Lessons Md */
            lessons_md: string | null;
            /** Miner Output */
            miner_output: {
                [key: string]: unknown;
            } | null;
            /** N Trades */
            n_trades: number;
            /** N Virtual */
            n_virtual: number;
            /** Status */
            status: string;
            /** Trigger */
            trigger: string;
            /** Validation */
            validation: {
                [key: string]: unknown;
            } | null;
            /**
             * Window From
             * Format: date-time
             */
            window_from: string;
            /**
             * Window To
             * Format: date-time
             */
            window_to: string;
        };
        /** AuditRunOut */
        AuditRunOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** N Trades */
            n_trades: number;
            /** N Virtual */
            n_virtual: number;
            /** Status */
            status: string;
            /** Trigger */
            trigger: string;
            /**
             * Window From
             * Format: date-time
             */
            window_from: string;
            /**
             * Window To
             * Format: date-time
             */
            window_to: string;
        };
        /** BarOut */
        BarOut: {
            /** Close */
            close: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Open */
            open: string;
            /** Tick Volume */
            tick_volume: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** BreakdownRow */
        BreakdownRow: {
            /** Expectancy R */
            expectancy_r: string | null;
            /** Key */
            key: string;
            /** Net Pnl */
            net_pnl: string;
            /** Trades */
            trades: number;
            /** Win Rate */
            win_rate: number | null;
        };
        /** CommandAccepted */
        CommandAccepted: {
            /** Command Id */
            command_id: string;
        };
        /** CommandIn */
        CommandIn: {
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Type */
            type: string;
        };
        /** CommandOut */
        CommandOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            } | null;
            /** Requested By */
            requested_by: string;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Type */
            type: string;
        };
        /** ConfigIn */
        ConfigIn: {
            /** Comment */
            comment?: string | null;
            /** Yaml */
            yaml: string;
        };
        /** ConfigOut */
        ConfigOut: {
            /** Json Schema */
            json_schema: {
                [key: string]: unknown;
            };
            /** Sha256 */
            sha256: string;
            /** Version Id */
            version_id: string | null;
            /** Yaml */
            yaml: string;
        };
        /** ConfigSaved */
        ConfigSaved: {
            /** Changed */
            changed: boolean;
            /** Command Id */
            command_id: string | null;
            /** Version Id */
            version_id: string;
        };
        /** ConfigVersionOut */
        ConfigVersionOut: {
            /** Comment */
            comment: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Id */
            id: string;
            /** Sha256 */
            sha256: string;
        };
        /** Costs */
        Costs: {
            /** Avg Entry Slippage Points */
            avg_entry_slippage_points: number | null;
            /** Avg Exit Slippage Points */
            avg_exit_slippage_points: number | null;
            /** Commission */
            commission: string;
            /** Fee */
            fee: string;
            /** Per Trade */
            per_trade: string | null;
            /** Swap */
            swap: string;
            /** Trades */
            trades: number;
        };
        /** DealOut */
        DealOut: {
            /** Commission */
            commission: string;
            /** Entry */
            entry: string;
            /** Fee */
            fee: string;
            /** Price */
            price: string;
            /** Profit */
            profit: string;
            /** Reason */
            reason: string;
            /** Side */
            side: string;
            /** Swap */
            swap: string;
            /** Ticket */
            ticket: number;
            /**
             * Time Utc
             * Format: date-time
             */
            time_utc: string;
            /** Volume */
            volume: string;
        };
        /** DecisionDossier */
        DecisionDossier: {
            /**
             * Bar Time
             * Format: date-time
             */
            bar_time: string;
            /** Calibrated Confidence */
            calibrated_confidence: number | null;
            /** Cost Usd */
            cost_usd: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Features */
            features?: {
                [key: string]: unknown;
            } | null;
            /** Final Confidence */
            final_confidence: number | null;
            /** Id */
            id: string;
            /** Intents */
            intents?: components["schemas"]["IntentOut"][];
            /** Latency Ms */
            latency_ms: number | null;
            /** Llm Calls */
            llm_calls?: components["schemas"]["LLMCallOut"][];
            /** Llm Confidence */
            llm_confidence: number | null;
            /** Model */
            model: string | null;
            /** Outcome */
            outcome: string;
            /** Penalty Points */
            penalty_points: number | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Proposal */
            proposal: {
                [key: string]: unknown;
            } | null;
            /** Reason Code */
            reason_code: string | null;
            /** Reason Detail */
            reason_detail: string | null;
            /** Risk Calc */
            risk_calc: {
                [key: string]: unknown;
            } | null;
            /** Risk Factor */
            risk_factor: string | null;
            /** Rules Matched */
            rules_matched: unknown[] | null;
            /** Setups */
            setups: unknown[] | null;
            /** Stage Reached */
            stage_reached: string;
            /** Symbol */
            symbol: string;
            /** Trigger Tf */
            trigger_tf: string;
        };
        /** DecisionOut */
        DecisionOut: {
            /**
             * Bar Time
             * Format: date-time
             */
            bar_time: string;
            /** Cost Usd */
            cost_usd: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Final Confidence */
            final_confidence: number | null;
            /** Id */
            id: string;
            /** Llm Confidence */
            llm_confidence: number | null;
            /** Model */
            model: string | null;
            /** Outcome */
            outcome: string;
            /** Reason Code */
            reason_code: string | null;
            /** Reason Detail */
            reason_detail: string | null;
            /** Stage Reached */
            stage_reached: string;
            /** Symbol */
            symbol: string;
            /** Trigger Tf */
            trigger_tf: string;
        };
        /**
         * Dimension
         * @enum {string}
         */
        Dimension: "symbol" | "setup_tag" | "session" | "regime" | "direction" | "confidence_bucket" | "rulebook_version";
        /** EngineStateOut */
        EngineStateOut: {
            /** Account Id */
            account_id: string;
            /** Halt Reason */
            halt_reason: string | null;
            /** Mode */
            mode: string;
            /** Rulebook Version */
            rulebook_version: number;
            /** State */
            state: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EquityPoint */
        EquityPoint: {
            /** Balance */
            balance: string;
            /** Day Pnl */
            day_pnl: string;
            /** Drawdown Pct */
            drawdown_pct: string;
            /** Equity */
            equity: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** FeatureOut */
        FeatureOut: {
            /** Bounds */
            bounds: number[] | null;
            /** Categories */
            categories: string[] | null;
            /** Description */
            description: string;
            /** Dtype */
            dtype: string;
            /** Name */
            name: string;
            /** Unit */
            unit: string;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartbeatOut */
        HeartbeatOut: {
            /**
             * Age S
             * @default 0
             */
            age_s: number;
            /** Component */
            component: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            } | null;
            /**
             * Last Beat At
             * Format: date-time
             */
            last_beat_at: string;
            /** Status */
            status: string;
        };
        /** IntentOut */
        IntentOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Fill Price */
            fill_price: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Price Ref */
            price_ref: string;
            /** Retcode */
            retcode: number | null;
            /** Side */
            side: string;
            /** Sl */
            sl: string | null;
            /** Status */
            status: string;
            /** Tp */
            tp: string | null;
            /** Volume */
            volume: string;
        };
        /** LLMCallOut */
        LLMCallOut: {
            /** Agent */
            agent: string;
            /** Cached Tokens */
            cached_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Cost Usd */
            cost_usd: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Id */
            id: string;
            /** Latency Ms */
            latency_ms: number | null;
            /** Messages */
            messages: unknown[] | null;
            /** Model */
            model: string;
            /** Parsed */
            parsed: {
                [key: string]: unknown;
            } | null;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Prompt Version */
            prompt_version: string;
            /** Response Text */
            response_text: string | null;
            /** Valid */
            valid: boolean;
        };
        /** LLMUsageRow */
        LLMUsageRow: {
            /** Agent */
            agent: string;
            /** Cache Hit Rate */
            cache_hit_rate: number;
            /** Calls */
            calls: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Cost Usd */
            cost_usd: string;
            /** Errors */
            errors: number;
            /** Latency P50 Ms */
            latency_p50_ms: number | null;
            /** Latency P95 Ms */
            latency_p95_ms: number | null;
            /** Model */
            model: string;
            /** Prompt Tokens */
            prompt_tokens: number;
        };
        /** LimitHeadroom */
        LimitHeadroom: {
            /** Limit Pct */
            limit_pct: string;
            /** Name */
            name: string;
            /** Used Pct */
            used_pct: string;
        };
        /** LogLine */
        LogLine: {
            /** Component */
            component: string | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Event */
            event: string | null;
            /** Level */
            level: string | null;
            /** Ts */
            ts: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
        };
        /** Marker */
        Marker: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Price */
            price: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** Me */
        Me: {
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Reauth Fresh */
            reauth_fresh: boolean;
            /**
             * Reauth Until
             * Format: date-time
             */
            reauth_until: string;
            /**
             * User
             * @default operator
             */
            user: string;
        };
        /** Page[DecisionOut] */
        Page_DecisionOut_: {
            /** Items */
            items: components["schemas"]["DecisionOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[TradeOut] */
        Page_TradeOut_: {
            /** Items */
            items: components["schemas"]["TradeOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[VirtualTradeOut] */
        Page_VirtualTradeOut_: {
            /** Items */
            items: components["schemas"]["VirtualTradeOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** PositionOut */
        PositionOut: {
            /** Age Minutes */
            age_minutes: number;
            /** Decision Id */
            decision_id: string | null;
            /** Last Price */
            last_price: string | null;
            /** Open Price */
            open_price: string;
            /**
             * Open Time
             * Format: date-time
             */
            open_time: string;
            /** Position Id */
            position_id: number;
            /** R Now */
            r_now: string | null;
            /** Setup Tag */
            setup_tag: string | null;
            /** Side */
            side: string;
            /** Sl */
            sl: string | null;
            /** Status */
            status: string;
            /** Symbol */
            symbol: string;
            /** Thesis */
            thesis: string | null;
            /** Tp */
            tp: string | null;
            /** Trade Id */
            trade_id: string;
            /** Volume */
            volume: string;
        };
        /** RuleCreated */
        RuleCreated: {
            /** Rule Id */
            rule_id: string;
            /** Status */
            status: string;
            /** Version */
            version: number;
        };
        /** RuleDetail */
        RuleDetail: {
            /** Matches */
            matches: components["schemas"]["RuleMatch"][];
            rule: components["schemas"]["RuleOut"];
            /** Versions */
            versions: components["schemas"]["RuleOut"][];
        };
        /**
         * RuleIn
         * @description An operator-authored rule: it becomes a CANDIDATE and goes through the same validator.
         */
        RuleIn: {
            /** Action */
            action?: {
                [key: string]: unknown;
            };
            /** Conditions */
            conditions: {
                [key: string]: unknown;
            };
            /** Hypothesis */
            hypothesis: string;
            /** Scope */
            scope?: {
                [key: string]: unknown;
            };
        };
        /** RuleMatch */
        RuleMatch: {
            /**
             * Bar Time
             * Format: date-time
             */
            bar_time: string;
            /** Decision Id */
            decision_id: string;
            /** Matched */
            matched: boolean;
            /** Mode */
            mode: string;
            /** Outcome */
            outcome: string;
            /** R */
            r: string | null;
            /** Symbol */
            symbol: string;
        };
        /** RuleOut */
        RuleOut: {
            /** Action */
            action?: {
                [key: string]: unknown;
            };
            /** Activated At */
            activated_at: string | null;
            /** Approved By */
            approved_by: string | null;
            /** Audit Run Id */
            audit_run_id: string | null;
            /**
             * Awaiting Approval
             * @default false
             */
            awaiting_approval: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dsl */
            dsl: {
                [key: string]: unknown;
            };
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            } | null;
            /** Expires At */
            expires_at: string | null;
            /** Hypothesis */
            hypothesis: string | null;
            /** Origin */
            origin: string;
            /** Retire Reason */
            retire_reason: string | null;
            /** Retired At */
            retired_at: string | null;
            /** Review At */
            review_at: string | null;
            /** Rule Id */
            rule_id: string;
            /** Shadow Started At */
            shadow_started_at: string | null;
            /** Status */
            status: string;
            /**
             * Text
             * @default
             */
            text: string;
            /** Version */
            version: number;
        };
        /**
         * RuleStatus
         * @description docs/02 §2.3.
         * @enum {string}
         */
        RuleStatus: "CANDIDATE" | "REJECTED" | "SHADOW" | "ACTIVE" | "RETIRED";
        /** RulebookDiff */
        RulebookDiff: {
            /** Activated */
            activated: string[];
            /** Deactivated */
            deactivated: string[];
            /** Previous */
            previous: number | null;
            /** Reason */
            reason: string;
            /** Shadowed */
            shadowed: string[];
            /** Unshadowed */
            unshadowed: string[];
            /** Version */
            version: number;
        };
        /** RulebookVersionOut */
        RulebookVersionOut: {
            /** Active Rules */
            active_rules: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reason */
            reason: string;
            /** Shadow Rules */
            shadow_rules: string[];
            /** Version */
            version: number;
        };
        /** SessionInfo */
        SessionInfo: {
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Reauth Until
             * Format: date-time
             */
            reauth_until: string;
        };
        /** Summary */
        Summary: {
            /** Avg Cost */
            avg_cost: string | null;
            /** Expectancy R */
            expectancy_r: string | null;
            /** Max Drawdown */
            max_drawdown: string;
            /** Net Pnl */
            net_pnl: string;
            /** Profit Factor */
            profit_factor: number | null;
            /** R Total */
            r_total: string;
            /** Sharpe Daily */
            sharpe_daily: number | null;
            /** Trades */
            trades: number;
            /** Trades Per Day */
            trades_per_day: number;
            /** Win Rate */
            win_rate: number | null;
        };
        /** SystemOut */
        SystemOut: {
            engine: components["schemas"]["EngineStateOut"] | null;
            /** Engine Stale */
            engine_stale: boolean;
            /** Heartbeats */
            heartbeats: components["schemas"]["HeartbeatOut"][];
            /** Llm Budget Usd */
            llm_budget_usd: string;
            /** Llm Spent Today Usd */
            llm_spent_today_usd: string;
            /**
             * Now
             * Format: date-time
             */
            now: string;
            versions: components["schemas"]["Versions"];
        };
        /** TradeDossier */
        TradeDossier: {
            /** Bars */
            bars?: components["schemas"]["BarOut"][];
            /** Bars Held */
            bars_held: number | null;
            /** Close Price Vwap */
            close_price_vwap: string | null;
            /** Close Reason */
            close_reason: string | null;
            /** Close Time */
            close_time: string | null;
            /** Commission */
            commission: string | null;
            /** Deals */
            deals?: components["schemas"]["DealOut"][];
            decision?: components["schemas"]["DecisionDossier"] | null;
            /** Decision Id */
            decision_id: string | null;
            /** Entry Slippage Points */
            entry_slippage_points: number | null;
            /** Exit Slippage Points */
            exit_slippage_points: number | null;
            /** Fee */
            fee: string | null;
            /** Gross Profit */
            gross_profit: string | null;
            /** Holding Minutes */
            holding_minutes: number | null;
            /** Id */
            id: string;
            /** Initial Risk Money */
            initial_risk_money: string | null;
            /** Initial Sl */
            initial_sl: string | null;
            /** Initial Tp */
            initial_tp: string | null;
            /** Mae R */
            mae_r: string | null;
            /** Markers */
            markers?: components["schemas"]["Marker"][];
            /** Mfe R */
            mfe_r: string | null;
            /** Net Pnl */
            net_pnl: string | null;
            /** Open Price */
            open_price: string;
            /**
             * Open Time
             * Format: date-time
             */
            open_time: string;
            /** Outcome */
            outcome: string | null;
            /** Position Id */
            position_id: number;
            /** R Multiple */
            r_multiple: string | null;
            /** Setup Tag */
            setup_tag: string | null;
            /** Side */
            side: string;
            /** Status */
            status: string;
            /** Swap */
            swap: string | null;
            /** Symbol */
            symbol: string;
            /** Volume Opened */
            volume_opened: string;
        };
        /** TradeOut */
        TradeOut: {
            /** Close Price Vwap */
            close_price_vwap: string | null;
            /** Close Reason */
            close_reason: string | null;
            /** Close Time */
            close_time: string | null;
            /** Decision Id */
            decision_id: string | null;
            /** Holding Minutes */
            holding_minutes: number | null;
            /** Id */
            id: string;
            /** Mae R */
            mae_r: string | null;
            /** Mfe R */
            mfe_r: string | null;
            /** Net Pnl */
            net_pnl: string | null;
            /** Open Price */
            open_price: string;
            /**
             * Open Time
             * Format: date-time
             */
            open_time: string;
            /** Outcome */
            outcome: string | null;
            /** Position Id */
            position_id: number;
            /** R Multiple */
            r_multiple: string | null;
            /** Setup Tag */
            setup_tag: string | null;
            /** Side */
            side: string;
            /** Status */
            status: string;
            /** Symbol */
            symbol: string;
            /** Volume Opened */
            volume_opened: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Versions */
        Versions: {
            /** Config Sha256 */
            config_sha256: string | null;
            /** Config Version */
            config_version: string | null;
            /** Feature Set */
            feature_set: number;
            /** Prompts */
            prompts: string[];
            /** Rulebook */
            rulebook: number;
        };
        /** VirtualTradeOut */
        VirtualTradeOut: {
            /** Arm */
            arm: string;
            /** Blocked By */
            blocked_by: string | null;
            /** Decision Id */
            decision_id: string;
            /** Entry Price */
            entry_price: string | null;
            /**
             * Entry Time
             * Format: date-time
             */
            entry_time: string;
            /** Exit Reason */
            exit_reason: string | null;
            /** Exit Time */
            exit_time: string | null;
            /** Id */
            id: string;
            /** R Multiple */
            r_multiple: string | null;
            /** Setup Tag */
            setup_tag: string | null;
            /** Side */
            side: string;
            /** Status */
            status: string;
            /** Symbol */
            symbol: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    account_api_account_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
        };
    };
    breakdown_api_analytics_breakdown_get: {
        parameters: {
            query: {
                dim: components["schemas"]["Dimension"];
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    costs_api_analytics_costs_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Costs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_analytics_summary_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audits_api_audits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRunOut"][];
                };
            };
        };
    };
    run_audit_api_audits_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAccepted"];
                };
            };
        };
    };
    audit_api_audits__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reauth_api_auth_reauth_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bars_api_bars_get: {
        parameters: {
            query: {
                symbol: string;
                tf?: string;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    command_api_commands__command_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                command_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    put_config_api_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSaved"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldError"][];
                };
            };
        };
    };
    config_versions_api_config_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"][];
                };
            };
        };
    };
    decisions_api_decisions_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                outcome?: string | null;
                reason?: string | null;
                from?: string | null;
                to?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DecisionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_api_decisions__decision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionDossier"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    engine_command_api_engine_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    equity_api_equity_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                granularity?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquityPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vault_exports_api_exports_vault_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    vault_export_api_exports_vault__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    features_api_features_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureOut"][];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    llm_usage_api_llm_usage_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMUsageRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logs_api_logs_get: {
        parameters: {
            query?: {
                level?: string | null;
                component?: string | null;
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogLine"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    positions_api_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"][];
                };
            };
        };
    };
    close_position_api_positions__position_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rulebook_versions_api_rulebook_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulebookVersionOut"][];
                };
            };
        };
    };
    rulebook_diff_api_rulebook_versions__version__diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulebookDiff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rules_api_rules_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RuleStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rule_api_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_rules__rule_id__approve_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_rules__rule_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_api_rules__rule_id__retire_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_api_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOut"];
                };
            };
        };
    };
    trades_api_trades_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                setup?: string | null;
                outcome?: string | null;
                from?: string | null;
                to?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TradeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trade_api_trades__trade_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeDossier"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    virtual_trades_api_virtual_trades_get: {
        parameters: {
            query?: {
                arm?: string | null;
                status?: string | null;
                symbol?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_VirtualTradeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
