"""initial schema

Revision ID: 27e75f1ca40c
Revises:
Create Date: 2026-09-28 04:45:40.950998

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import aifund.persistence.types

# revision identifiers, used by Alembic.
revision: str = "27e75f1ca40c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("ts", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_ts"), ["ts"], unique=False)

    op.create_table(
        "audit_runs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("window_from", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("window_to", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("n_trades", sa.Integer(), nullable=False),
        sa.Column("n_virtual", sa.Integer(), nullable=False),
        sa.Column("miner_output", sa.JSON(), nullable=True),
        sa.Column("candidates", sa.JSON(), nullable=True),
        sa.Column("validation", sa.JSON(), nullable=True),
        sa.Column("lessons_md", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("finished_at", aifund.persistence.types.UtcDateTime(length=27), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_runs")),
    )
    op.create_table(
        "calibration_models",
        sa.Column("version", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column("n_samples", sa.Integer(), nullable=False),
        sa.Column("brier_before", sa.Float(), nullable=True),
        sa.Column("brier_after", sa.Float(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_calibration_models")),
    )
    op.create_table(
        "commands",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "DONE",
                "FAILED",
                name="commandstatus",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("requested_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("started_at", aifund.persistence.types.UtcDateTime(length=27), nullable=True),
        sa.Column("finished_at", aifund.persistence.types.UtcDateTime(length=27), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commands")),
    )
    with op.batch_alter_table("commands", schema=None) as batch_op:
        batch_op.create_index("ix_commands_status_created", ["status", "created_at"], unique=False)

    op.create_table(
        "config_versions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("yaml_text", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_config_versions")),
    )
    with op.batch_alter_table("config_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_config_versions_sha256"), ["sha256"], unique=False)

    op.create_table(
        "deals",
        sa.Column("ticket", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("order", sa.BigInteger(), nullable=False),
        sa.Column("position_id", sa.BigInteger(), nullable=False),
        sa.Column("time_utc", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("time_server", sa.BigInteger(), nullable=False),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="side", native_enum=False, create_constraint=True, length=24),
            nullable=False,
        ),
        sa.Column(
            "entry",
            sa.Enum(
                "IN",
                "OUT",
                "INOUT",
                "OUT_BY",
                name="dealentry",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "reason",
            sa.Enum(
                "CLIENT",
                "MOBILE",
                "WEB",
                "EXPERT",
                "SL",
                "TP",
                "SO",
                "ROLLOVER",
                "VMARGIN",
                "SPLIT",
                "OTHER",
                name="dealreason",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("magic", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("volume", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("price", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("profit", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("commission", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("swap", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("fee", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("comment", sa.String(length=64), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("ticket", name=op.f("pk_deals")),
    )
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_deals_position_id"), ["position_id"], unique=False)

    op.create_table(
        "equity_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("ts", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("balance", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("equity", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("margin", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("free_margin", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("open_risk_money", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("open_notional", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.Column("day_pnl", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("drawdown_pct", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equity_snapshots")),
    )
    with op.batch_alter_table("equity_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_equity_snapshots_ts"), ["ts"], unique=False)

    op.create_table(
        "events",
        sa.Column("seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_events")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_ts"), ["ts"], unique=False)

    op.create_table(
        "feature_snapshots",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("trigger_tf", sa.String(length=4), nullable=False),
        sa.Column("bar_time", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("feature_set_version", sa.Integer(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("bars_ref", sa.JSON(), nullable=False),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_snapshots")),
        sa.UniqueConstraint(
            "symbol",
            "trigger_tf",
            "bar_time",
            "feature_set_version",
            name=op.f("uq_feature_snapshots_symbol_trigger_tf_bar_time_feature_set_version"),
        ),
    )
    op.create_table(
        "heartbeats",
        sa.Column("component", sa.String(length=64), nullable=False),
        sa.Column("last_beat_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("component", name=op.f("pk_heartbeats")),
    )
    op.create_table(
        "rulebook_versions",
        sa.Column("version", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("active_rules", sa.JSON(), nullable=False),
        sa.Column("shadow_rules", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_rulebook_versions")),
    )
    op.create_table(
        "symbols",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("canonical", sa.String(length=16), nullable=False),
        sa.Column("asset_class", sa.String(length=16), nullable=False),
        sa.Column("digits", sa.Integer(), nullable=False),
        sa.Column("point", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("tick_size", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("tick_value", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("contract_size", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("volume_min", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("volume_max", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("volume_step", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("stops_level_points", sa.Integer(), nullable=False),
        sa.Column("freeze_level_points", sa.Integer(), nullable=False),
        sa.Column("filling_mode_flags", sa.Integer(), nullable=False),
        sa.Column("currency_profit", sa.String(length=8), nullable=False),
        sa.Column("currency_margin", sa.String(length=8), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.Column("refreshed_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.PrimaryKeyConstraint("symbol", name=op.f("pk_symbols")),
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("trigger_tf", sa.String(length=4), nullable=False),
        sa.Column("bar_time", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("snapshot_id", sa.String(length=26), nullable=True),
        sa.Column("stage_reached", sa.String(length=16), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "SKIPPED",
                "NO_SETUP",
                "HOLD",
                "INVALID",
                "RULE_BLOCKED",
                "BELOW_THRESHOLD",
                "RISK_REJECTED",
                "ORDERED",
                "ERROR",
                name="decisionoutcome",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("reason_code", sa.String(length=40), nullable=True),
        sa.Column("reason_detail", sa.Text(), nullable=True),
        sa.Column("setups", sa.JSON(), nullable=True),
        sa.Column("proposal", sa.JSON(), nullable=True),
        sa.Column("llm_confidence", sa.Integer(), nullable=True),
        sa.Column("calibrated_confidence", sa.Integer(), nullable=True),
        sa.Column("penalty_points", sa.Integer(), nullable=True),
        sa.Column("final_confidence", sa.Integer(), nullable=True),
        sa.Column("risk_factor", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("rules_matched", sa.JSON(), nullable=True),
        sa.Column("lessons_shown", sa.JSON(), nullable=True),
        sa.Column("rulebook_version", sa.Integer(), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("config_version_id", sa.String(length=26), nullable=True),
        sa.Column("risk_calc", sa.JSON(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("cost_usd", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["config_version_id"],
            ["config_versions.id"],
            name=op.f("fk_decisions_config_version_id_config_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["feature_snapshots.id"], name=op.f("fk_decisions_snapshot_id_feature_snapshots")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
    )
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.create_index("ix_decisions_outcome_created", ["outcome", "created_at"], unique=False)
        batch_op.create_index("ix_decisions_symbol_bar", ["symbol", "bar_time"], unique=False)

    op.create_table(
        "engine_state",
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "STOPPED",
                "STARTING",
                "RUNNING",
                "PAUSED",
                "HALTED",
                "FLATTENING",
                name="enginestate",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum(
                "SIM",
                "PAPER",
                "DEMO",
                "LIVE",
                name="mode",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("halt_reason", sa.String(length=500), nullable=True),
        sa.Column("day_start_equity", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("peak_equity", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("config_version_id", sa.String(length=26), nullable=True),
        sa.Column("rulebook_version", sa.Integer(), nullable=False),
        sa.Column("updated_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["config_version_id"],
            ["config_versions.id"],
            name=op.f("fk_engine_state_config_version_id_config_versions"),
        ),
        sa.PrimaryKeyConstraint("account_id", name=op.f("pk_engine_state")),
    )
    op.create_table(
        "rules",
        sa.Column("rule_id", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CANDIDATE",
                "REJECTED",
                "SHADOW",
                "ACTIVE",
                "RETIRED",
                name="rulestatus",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("dsl", sa.JSON(), nullable=False),
        sa.Column("dsl_sha256", sa.String(length=64), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("audit_run_id", sa.String(length=26), nullable=True),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("approved_at", aifund.persistence.types.UtcDateTime(length=27), nullable=True),
        sa.Column("shadow_started_at", aifund.persistence.types.UtcDateTime(length=27), nullable=True),
        sa.Column("activated_at", aifund.persistence.types.UtcDateTime(length=27), nullable=True),
        sa.Column("review_at", aifund.persistence.types.UtcDateTime(length=27), nullable=True),
        sa.Column("expires_at", aifund.persistence.types.UtcDateTime(length=27), nullable=True),
        sa.Column("retired_at", aifund.persistence.types.UtcDateTime(length=27), nullable=True),
        sa.Column("retire_reason", sa.Text(), nullable=True),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_run_id"], ["audit_runs.id"], name=op.f("fk_rules_audit_run_id_audit_runs")
        ),
        sa.PrimaryKeyConstraint("rule_id", "version", name=op.f("pk_rules")),
    )
    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rules_dsl_sha256"), ["dsl_sha256"], unique=False)
        batch_op.create_index("ix_rules_status", ["status"], unique=False)

    op.create_table(
        "order_intents",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("idempotency_key", sa.String(length=24), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("decision_id", sa.String(length=26), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "OPEN",
                "CLOSE",
                "REVERSE_CLOSE",
                "MODIFY_SLTP",
                "FLATTEN",
                name="intentkind",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="side", native_enum=False, create_constraint=True, length=24),
            nullable=False,
        ),
        sa.Column("volume", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("price_ref", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("sl", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("tp", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("sl_distance", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("tp_distance", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("risk_money", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("risk_pct", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("comment", sa.String(length=31), nullable=False),
        sa.Column("magic", sa.BigInteger(), nullable=False),
        sa.Column("position_ticket", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CHECK_FAILED",
                "SENT",
                "RETRYING",
                "FILLED",
                "REJECTED",
                "UNKNOWN",
                name="intentstatus",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("retcode", sa.Integer(), nullable=True),
        sa.Column("retcode_name", sa.String(length=64), nullable=True),
        sa.Column("broker_comment", sa.String(length=255), nullable=True),
        sa.Column("order_ticket", sa.BigInteger(), nullable=True),
        sa.Column("deal_ticket", sa.BigInteger(), nullable=True),
        sa.Column("position_id", sa.BigInteger(), nullable=True),
        sa.Column("fill_price", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("fill_volume", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("slippage_points", sa.Integer(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("sent_at", aifund.persistence.types.UtcDateTime(length=27), nullable=True),
        sa.Column("resolved_at", aifund.persistence.types.UtcDateTime(length=27), nullable=True),
        sa.ForeignKeyConstraint(
            ["decision_id"], ["decisions.id"], name=op.f("fk_order_intents_decision_id_decisions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_intents")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_order_intents_idempotency_key")),
    )
    with op.batch_alter_table("order_intents", schema=None) as batch_op:
        batch_op.create_index("ix_order_intents_symbol_status", ["symbol", "status"], unique=False)

    op.create_table(
        "rule_evaluations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("decision_id", sa.String(length=26), nullable=False),
        sa.Column("rule_id", sa.String(length=16), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("matched", sa.Boolean(), nullable=False),
        sa.Column("action_applied", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["decision_id"], ["decisions.id"], name=op.f("fk_rule_evaluations_decision_id_decisions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_evaluations")),
    )
    with op.batch_alter_table("rule_evaluations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rule_evaluations_decision_id"), ["decision_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rule_evaluations_rule_id"), ["rule_id"], unique=False)

    op.create_table(
        "virtual_trades",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("decision_id", sa.String(length=26), nullable=False),
        sa.Column("snapshot_id", sa.String(length=26), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="side", native_enum=False, create_constraint=True, length=24),
            nullable=False,
        ),
        sa.Column("setup_tag", sa.String(length=40), nullable=True),
        sa.Column("entry_time", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("entry_price", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("sl", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("tp", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("exit_time", aifund.persistence.types.UtcDateTime(length=27), nullable=True),
        sa.Column("exit_price", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("exit_reason", sa.String(length=24), nullable=True),
        sa.Column("r_multiple", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("mae_r", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("mfe_r", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("blocked_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"], ["decisions.id"], name=op.f("fk_virtual_trades_decision_id_decisions")
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["feature_snapshots.id"],
            name=op.f("fk_virtual_trades_snapshot_id_feature_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_virtual_trades")),
    )
    with op.batch_alter_table("virtual_trades", schema=None) as batch_op:
        batch_op.create_index("ix_virtual_trades_status", ["status"], unique=False)

    op.create_table(
        "trades",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("position_id", sa.BigInteger(), nullable=False),
        sa.Column("intent_id", sa.String(length=26), nullable=True),
        sa.Column("decision_id", sa.String(length=26), nullable=True),
        sa.Column("snapshot_id", sa.String(length=26), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="side", native_enum=False, create_constraint=True, length=24),
            nullable=False,
        ),
        sa.Column("setup_tag", sa.String(length=40), nullable=True),
        sa.Column("trigger_tf", sa.String(length=4), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLOSED",
                "ORPHAN_OPEN",
                "ORPHAN_CLOSED",
                name="tradestatus",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("open_time", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("open_price", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("volume_opened", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("volume_open_now", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("initial_sl", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("initial_tp", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("current_sl", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("current_tp", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("initial_risk_money", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("close_time", aifund.persistence.types.UtcDateTime(length=27), nullable=True),
        sa.Column("close_price_vwap", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("close_reason", sa.String(length=24), nullable=True),
        sa.Column("gross_profit", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("commission", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("swap", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("fee", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("net_pnl", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("r_multiple", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("mae_r", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("mfe_r", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("bars_held", sa.Integer(), nullable=True),
        sa.Column("holding_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "WIN",
                "LOSS",
                "BREAKEVEN",
                name="tradeoutcome",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=True,
        ),
        sa.Column("review_status", sa.String(length=16), nullable=False),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("updated_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"], ["decisions.id"], name=op.f("fk_trades_decision_id_decisions")
        ),
        sa.ForeignKeyConstraint(
            ["intent_id"], ["order_intents.id"], name=op.f("fk_trades_intent_id_order_intents")
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["feature_snapshots.id"], name=op.f("fk_trades_snapshot_id_feature_snapshots")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
        sa.UniqueConstraint("position_id", name=op.f("uq_trades_position_id")),
    )
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.create_index("ix_trades_status_symbol", ["status", "symbol"], unique=False)

    op.create_table(
        "llm_calls",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("agent", sa.String(length=32), nullable=False),
        sa.Column("decision_id", sa.String(length=26), nullable=True),
        sa.Column("trade_id", sa.String(length=26), nullable=True),
        sa.Column("audit_run_id", sa.String(length=26), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("model_reported", sa.String(length=128), nullable=True),
        sa.Column("prompt_template", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("prompt_sha256", sa.String(length=64), nullable=False),
        sa.Column("messages", sa.JSON(), nullable=True),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("parsed", sa.JSON(), nullable=True),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", aifund.persistence.types.DecimalText(length=64), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_run_id"], ["audit_runs.id"], name=op.f("fk_llm_calls_audit_run_id_audit_runs")
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"], ["decisions.id"], name=op.f("fk_llm_calls_decision_id_decisions")
        ),
        sa.ForeignKeyConstraint(["trade_id"], ["trades.id"], name=op.f("fk_llm_calls_trade_id_trades")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.create_index("ix_llm_calls_agent_created", ["agent", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_calls_decision_id"), ["decision_id"], unique=False)

    op.create_table(
        "trade_reviews",
        sa.Column("trade_id", sa.String(length=26), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("thesis_verdict", sa.String(length=16), nullable=False),
        sa.Column("execution_quality", sa.Integer(), nullable=False),
        sa.Column("lesson", sa.Text(), nullable=False),
        sa.Column("llm_call_id", sa.String(length=26), nullable=True),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["llm_call_id"], ["llm_calls.id"], name=op.f("fk_trade_reviews_llm_call_id_llm_calls")
        ),
        sa.ForeignKeyConstraint(["trade_id"], ["trades.id"], name=op.f("fk_trade_reviews_trade_id_trades")),
        sa.PrimaryKeyConstraint("trade_id", name=op.f("pk_trade_reviews")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trade_reviews")
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_calls_decision_id"))
        batch_op.drop_index("ix_llm_calls_agent_created")

    op.drop_table("llm_calls")
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_index("ix_trades_status_symbol")

    op.drop_table("trades")
    with op.batch_alter_table("virtual_trades", schema=None) as batch_op:
        batch_op.drop_index("ix_virtual_trades_status")

    op.drop_table("virtual_trades")
    with op.batch_alter_table("rule_evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rule_evaluations_rule_id"))
        batch_op.drop_index(batch_op.f("ix_rule_evaluations_decision_id"))

    op.drop_table("rule_evaluations")
    with op.batch_alter_table("order_intents", schema=None) as batch_op:
        batch_op.drop_index("ix_order_intents_symbol_status")

    op.drop_table("order_intents")
    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.drop_index("ix_rules_status")
        batch_op.drop_index(batch_op.f("ix_rules_dsl_sha256"))

    op.drop_table("rules")
    op.drop_table("engine_state")
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.drop_index("ix_decisions_symbol_bar")
        batch_op.drop_index("ix_decisions_outcome_created")

    op.drop_table("decisions")
    op.drop_table("symbols")
    op.drop_table("rulebook_versions")
    op.drop_table("heartbeats")
    op.drop_table("feature_snapshots")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_ts"))

    op.drop_table("events")
    with op.batch_alter_table("equity_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_equity_snapshots_ts"))

    op.drop_table("equity_snapshots")
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deals_position_id"))

    op.drop_table("deals")
    with op.batch_alter_table("config_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_config_versions_sha256"))

    op.drop_table("config_versions")
    with op.batch_alter_table("commands", schema=None) as batch_op:
        batch_op.drop_index("ix_commands_status_created")

    op.drop_table("commands")
    op.drop_table("calibration_models")
    op.drop_table("audit_runs")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_ts"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
