"""api sessions and bar cache

Dashboard logins (token hash, CSRF token, expiry, last password entry) and the closed bars the engine has
read, for the dashboard's charts (roadmap 6.1, 6.2).

Revision ID: b56f9b78b406
Revises: b7d2e4f9c1a3
Create Date: 2026-09-29

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import aifund.persistence.types

# revision identifiers, used by Alembic.
revision: str = "b56f9b78b406"
down_revision: str | Sequence[str] | None = "b7d2e4f9c1a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_sessions",
        sa.Column("token_sha256", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("created_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("expires_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("reauth_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("last_seen_at", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("token_sha256", name=op.f("pk_api_sessions")),
    )
    with op.batch_alter_table("api_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_sessions_expires_at"), ["expires_at"], unique=False)

    op.create_table(
        "bar_cache",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=4), nullable=False),
        sa.Column("time", aifund.persistence.types.UtcDateTime(length=27), nullable=False),
        sa.Column("open", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("high", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("low", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("close", aifund.persistence.types.DecimalText(length=64), nullable=False),
        sa.Column("tick_volume", sa.BigInteger(), nullable=False),
        sa.Column("spread_points", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("symbol", "timeframe", "time", name=op.f("pk_bar_cache")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bar_cache")
    with op.batch_alter_table("api_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_sessions_expires_at"))

    op.drop_table("api_sessions")
    # ### end Alembic commands ###
